spring.application.name=kafka-capstone-project
spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.example.kafkacapstoneproject.serdes.JsonSerializer
spring.kafka.producer.acks=1
spring.kafka.streams.application-id=streams-metrics
spring.kafka.streams.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.processing.guarantee=exactly_once_v2
