bootstrap.servers=broker-1:19092,broker-2:19092,broker-3:19092
group.id=file-writer-connector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
config.storage.topic=file-writer-connector-configs
config.storage.replication.factor=2
offset.storage.topic=file-writer-connector-offsets
offset.storage.replication.factor=2
status.storage.topic=file-writer-connector-status
status.storage.replication.factor=2
offset.flush.interval.ms=10000
plugin.path=/opt/kafka/libs/connect-file-4.1.1.jar
